AllCops:
  TargetRubyVersion: 2.1

# Allow lines up to 120 characters instead of the default 80.
Metrics/LineLength:
  Description: Limit lines to 120 characters.
  Enabled: true
  Max: 120

# Allow parentheses without arguments.
Style/MethodCallParentheses:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false

# Allow multiple empty lines for formatting.
Style/EmptyLines:
  Enabled: false

# Don't check the length of methods.
Metrics/MethodLength:
  Enabled: false

# Allow if !condition.
Style/NegatedIf:
  Enabled: false

# Allow explicit returns.
Style/RedundantReturn:
  Enabled: false

# Trailing commas are more git-friendly in case new elements are added.
Style/TrailingCommaInLiteral:
  Enabled: false
